from socket import gethostname

from lib import filesystem


def _export(tmp_path, custom_hosts=None, blocked_hosts=(), blacklisted_hosts=()):
    hosts_file = tmp_path / 'hosts'
    filesystem.export_hosts_file(
        str(hosts_file), custom_hosts or {}, list(blocked_hosts), list(blacklisted_hosts)
    )

    return hosts_file.read_text()


def test_headers_are_always_written(tmp_path):
    content = _export(tmp_path)

    assert content.startswith('# This hosts file was generated by AdAway.py')
    assert f'127.0.0.1 {gethostname()}\n' in content
    assert '127.0.0.1 localhost\n' in content
    assert '::1       localhost\n' in content


def test_custom_hosts_are_written(tmp_path):
    content = _export(tmp_path, custom_hosts={'mydomain.example': '127.0.0.1'})

    assert '# Custom hosts\n' in content
    assert '127.0.0.1\tmydomain.example\n' in content


def test_blacklisted_hosts_are_written(tmp_path):
    content = _export(tmp_path, blacklisted_hosts=['nasty.example'])

    assert '# Blacklisted hosts\n' in content
    assert '0.0.0.0\tnasty.example\n' in content


def test_blocked_hosts_are_written_from_plain_strings(tmp_path):
    content = _export(tmp_path, blocked_hosts=['ads.example', 'tracker.example'])

    assert '0.0.0.0\tads.example\n' in content
    assert '0.0.0.0\ttracker.example\n' in content


def test_empty_sections_are_omitted(tmp_path):
    content = _export(tmp_path)

    assert '# Custom hosts' not in content
    assert '# Blacklisted hosts' not in content


def test_export_overwrites_a_previous_run(tmp_path):
    hosts_file = tmp_path / 'hosts'
    hosts_file.write_text('0.0.0.0\tstale.example\n')

    filesystem.export_hosts_file(str(hosts_file), {}, ['ads.example'], [])

    assert 'stale.example' not in hosts_file.read_text()


def test_deactivate_writes_headers_only(tmp_path):
    hosts_file = tmp_path / 'hosts'
    filesystem.export_hosts_headers(str(hosts_file), {'mydomain.example': '127.0.0.1'})
    content = hosts_file.read_text()

    assert '127.0.0.1 localhost\n' in content
    assert '127.0.0.1\tmydomain.example\n' in content
    assert '0.0.0.0' not in content
